site:
  title: Antora Documentation POC
  start_page: getting-started::index.adoc

content:
  sources:
    - url: https://github.com/antoramvp/getting-started.git
      branches: main

    - url: https://github.com/antoramvp/pos-integration.git
      branches: main

    - url: https://github.com/antoramvp/api-docs.git
      branches:
        - v1.0
        - v2.0

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: partials/head-styles.hbs
    contents: |
      <link rel="stylesheet" href="{{{uiRootPath}}}/css/site.css">
      <style>
        .navbar {
          background: red !important;
        }
      </style>

output:
  dir: ./build/site
